name: build

on:
  push:
    tags: ["v*"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: https://gitea.com/spotdemo4/go-template/.github/actions/init@main

      - run: |
          mkdir binaries

          nix build .#linux-amd64
          tar czf ${{ github.event.repository.name }}-linux-amd64.tar.gz -C result/bin ${{ github.event.repository.name }}
          mv ${{ github.event.repository.name }}-linux-amd64.tar.gz binaries

          nix build .#linux-arm64
          tar czf ${{ github.event.repository.name }}-linux-arm64.tar.gz -C result/bin ${{ github.event.repository.name }}
          mv ${{ github.event.repository.name }}-linux-arm64.tar.gz binaries

          nix build .#linux-arm
          tar czf ${{ github.event.repository.name }}-linux-arm.tar.gz -C result/bin ${{ github.event.repository.name }}
          mv ${{ github.event.repository.name }}-linux-arm.tar.gz binaries

          nix build .#darwin-arm64
          tar czf ${{ github.event.repository.name }}-darwin-arm64.tar.gz -C result/bin ${{ github.event.repository.name }}
          mv ${{ github.event.repository.name }}-darwin-arm64.tar.gz binaries

          nix build .#windows-amd64
          zip -j ${{ github.event.repository.name }}-windows-amd64.zip result/bin/${{ github.event.repository.name }}.exe
          mv ${{ github.event.repository.name }}-windows-amd64.zip binaries

      - uses: https://gitea.com/actions/gitea-release-action@fe8e0322804b48e34e3bddbbf6335bd2b1046eb7 # v1
        with:
          files: |-
            binaries/*

  package:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: https://gitea.com/spotdemo4/go-template/.github/actions/init@main

      - uses: https://github.com/nicknovitski/nix-develop@9be7cfb4b10451d3390a75dc18ad0465bed4932a # v1.2.1
        with:
          arguments: ".#release"

      - name: Build & push images
        run: |
          nix build .#image

          mkdir -p /etc/containers
          curl -L -o /etc/containers/policy.json https://raw.githubusercontent.com/containers/image/main/default-policy.json

          ./result | gzip --fast | skopeo copy \
            --dest-creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} \
            docker-archive:/dev/stdin \
            docker://${{ github.server_url }}/${{ github.repository }}:${GITHUB_REF_NAME#v}
