name: update

on:
  schedule:
    - cron: "9 9 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: https://gitea.com/spotdemo4/go-template/.github/actions/init@main

      - uses: nicknovitski/nix-develop@9be7cfb4b10451d3390a75dc18ad0465bed4932a # v1.2.1
        with:
          arguments: ".#update"

      - name: Renovate
        env:
          RENOVATE_CONFIG_FILE: .gitea/renovate.json
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_GITHUB_COM_TOKEN: ${{ secrets.GH_TOKEN }}
        run: renovate
