name: vulnerable

on:
  schedule:
    - cron: "0 9 * * 0" # every day at 09:00 UTC
  workflow_dispatch:

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@2109e877d5ff4cd827944b51781cc6b1eac88a47 # v1.8.3
        with:
          token: ${{ secrets.READ_ONLY_TOKEN }}
          shell: vulnerable

      - run: govulncheck ./...

  flake:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@2109e877d5ff4cd827944b51781cc6b1eac88a47 # v1.8.3
        with:
          token: ${{ secrets.READ_ONLY_TOKEN }}
          shell: vulnerable

      - run: flake-checker -f
