name: vulnerable

on:
  schedule:
    - cron: "9 9 * * 0"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: https://gitea.com/spotdemo4/go-template/.github/actions/init@main

      - uses: https://github.com/nicknovitski/nix-develop@9be7cfb4b10451d3390a75dc18ad0465bed4932a # v1.2.1
        with:
          arguments: ".#vulnerable"

      - run: govulncheck ./...

  flake:
    runs-on: ubuntu-latest
    steps:
      - uses: https://gitea.com/spotdemo4/go-template/.github/actions/init@main

      - uses: nicknovitski/nix-develop@9be7cfb4b10451d3390a75dc18ad0465bed4932a # v1.2.1
        with:
          arguments: ".#vulnerable"

      - run: flake-checker -f
