name: vulnerable

on:
  schedule:
    - cron: "0 9 * * 0" # every day at 09:00 UTC
  workflow_dispatch:

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@ebb74f1642446e78bfeb82da93c87792f8ef81c3 # v1.8.5
        with:
          token: ${{ secrets.READ_ONLY_TOKEN }}
          shell: vulnerable

      - run: govulncheck ./...

  flake:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@ebb74f1642446e78bfeb82da93c87792f8ef81c3 # v1.8.5
        with:
          token: ${{ secrets.READ_ONLY_TOKEN }}
          shell: vulnerable

      - run: flake-checker -f
