name: vulnerable

on:
  schedule:
    - cron: "0 9 * * 0" # every day at 09:00 UTC
  workflow_dispatch:

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@448722165938617ea8b814719c33d73122390c9a # v1.2.0
        with:
          token: ${{ secrets.READ_ONLY_TOKEN }}
          shell: vulnerable

      - run: govulncheck ./...

  flake:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@448722165938617ea8b814719c33d73122390c9a # v1.2.0
        with:
          token: ${{ secrets.READ_ONLY_TOKEN }}
          shell: vulnerable

      - run: flake-checker -f
