name: "init"
description: "initialize nix"
runs:
  using: "composite"
  steps:
    - uses: https://github.com/actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - uses: https://github.com/DeterminateSystems/nix-installer-action@786fff0690178f1234e4e1fe9b536e94f5433196 # v20
      with:
        extra-conf: |
          extra-substituters = https://cache.trev.zip/nur
          extra-trusted-public-keys = nur:DoXGy0SJ+5udhvZgtzwEXhQMuOCFN7FSXRmtiZhF1Vw=

    - uses: https://github.com/spotdemo4/nix-simple-cache-action@8081a7be4147aab699a313ec0e53f937183437a7 # v1.5.2
