name: release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

concurrency:
  group: release

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  linux-amd64:
    name: linux amd64
    runs-on: ubuntu-24.04
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@757d5ba1fa0749e877484703bece0e17c7bd5670 # v1.43.0
        with:
          fetch_depth: 0
          shell: release

      - name: Release to GitHub
        run: flake-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REGISTRY: ghcr.io
          REGISTRY_USERNAME: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          PACKAGES: |
            images.x86_64-linux.default.x86_64-unknown-linux-musl
            packages.x86_64-linux.default.x86_64-unknown-linux-musl
            packages.x86_64-linux.default.x86_64-w64-mingw32

      - name: Publish to FlakeHub
        uses: DeterminateSystems/flakehub-push@71f57208810a5d299fc6545350981de98fdbc860 # v6
        with:
          visibility: public

  linux-arm64:
    name: linux arm64
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@757d5ba1fa0749e877484703bece0e17c7bd5670 # v1.43.0
        with:
          fetch_depth: 0
          shell: release

      - name: Release to GitHub
        run: flake-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REGISTRY: ghcr.io
          REGISTRY_USERNAME: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          PACKAGES: |
            images.aarch64-linux.default.aarch64-unknown-linux-musl
            images.aarch64-linux.default.armv7l-unknown-linux-musleabihf
            packages.aarch64-linux.default.aarch64-unknown-linux-musl
            packages.aarch64-linux.default.armv7l-unknown-linux-musleabihf

  darwin-arm64:
    name: darwin arm64
    runs-on: macos-26
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@757d5ba1fa0749e877484703bece0e17c7bd5670 # v1.43.0
        with:
          fetch_depth: 0
          shell: release

      - name: Release to GitHub
        run: flake-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REGISTRY: ghcr.io
          REGISTRY_USERNAME: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          PACKAGES: |
            packages.aarch64-darwin.default.arm64-apple-darwin
            packages.aarch64-darwin.default.x86_64-apple-darwin
